version: "2"

networks:
  internal:
    driver: bridge

services:
  union_php_apache:
    image: webdevops/php-apache:7.4
    tty: true
    volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../sistema:/var/www/html/sistema"
    ports:
      - "2080:80"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.unionbank.rule=Host(`unionbank.localhost`)
      - traefik.http.services.unionbank.loadbalancer.server.port=80

  # php_lsstar:
  #   build: .
  #   container_name: php_lsstar
  #   working_dir: /usr/share/nginx/html
  #   volumes:
  #     - ../:/usr/share/nginx/html
  #   #command: "php artisan serve --host=0.0.0.0 --port=2030"
  #   ports:
  #     - "2030:2030"
  #   networks:
  #     - lsstar
